server:
  tomcat:
    uri-encoding: UTF-8
  port: 8008
spring:
  zipkin:
    base-url: http://localhost:8888
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka
foo: iii222
